### ISSUE TITLE
Extension installed and configured but not working (no output)

### ISSUE THREAD

**Issue by harrchen88** [Azure-Samples/azure-devops-copilot-extension#16]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>Install the extension and configured the service url and API key, tried to generate test cases, nothing generated.

### Any log messages given by the failure
>Nothing

### Expected/desired behavior
>Test cases generated based on acceptance criteria

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by mahomedalid** [comment]
Could you provide a screenshot ?

**Comment by mahomedalid** [comment]
If you are still experiencing this issue, kindly re-open and add a screenshot or more information. Thanks.
